---
  - name: Git log sur l'instance lizmap PNG AVANT la MAJ
    command: "git log -n 1 --pretty=format:'%Cred%h%Creset %an: %s - %Creset %C(yellow)%d%Creset %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"
    args:
      chdir: /srv/lizmap_png/
    register: git_log_png
    changed_when: false

  - name: COMMIT en local sur la branche lizmap PNG 3.2
    debug: msg="{{ git_log_png.stdout }}"
    changed_when: false


  # Absence de module GIT merge dans Ansible

  - name: git fetch origin sur les instances lizmap
    become: true
    command: git fetch origin
    args:
      chdir: "{{ item }}"
    changed_when: false
    with_items:
      - /srv/lizmap_png/
      - /srv/lizmap_karunati/

  - name: git merge origin/release_3_2 sur les instances lizmap
    become: true
    command: git merge origin/release_3_2
    register: merge_result
    args:
      chdir: "{{ item }}"
    changed_when: "merge_result.stdout != 'Déjà à jour.'"
    with_items:
      - /srv/lizmap_png/
      - /srv/lizmap_karunati/

  - name: restart nginx
    become: true
    service: name=nginx state=restarted
    # when: "merge_result.stdout != 'Déjà à jour.'"

  - name: Git log sur l'instance lizmap PNG
    command: "git log -n 1 --pretty=format:'%Cred%h%Creset %an: %s - %Creset %C(yellow)%d%Creset %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"
    args:
      chdir: /srv/lizmap_png/
    register: git_log_png
    changed_when: false

  - name: Dernier commit sur la branche lizmap PNG 3.2
    debug: msg="{{ git_log_png.stdout }}"
    changed_when: false

  - name: Get QGIS Server version
    command: "apt policy qgis-server"
    register: apt_qgis_server
    changed_when: false

  - name: Check QGIS Server version
    debug: msg="{{ apt_qgis_server.stdout }}"
    changed_when: false

  - name: Check http://lizmap.pn971.net/
    uri:
      url: http://lizmap.pn971.net/

  - name: Check http://karunati.pn971.net/
    uri:
      url: http://karunati.pn971.net/

...
