  - name: git fetch origin-ssh sur naturaliz
    become: true
    command: git fetch origin-ssh
    args:
      chdir: /home/karuadmin/naturaliz
    changed_when: false

  - name: git merge origin-ssh/master sur naturaliz
    become: true
    command: git merge origin-ssh/master
    register: merge_result
    args:
      chdir: /home/karuadmin/naturaliz
    changed_when: "merge_result.stdout != 'Déjà à jour.'"

  - name: Copie de naturaliz vers karunati
    command: cp -R /home/karuadmin/naturaliz/. /srv/lizmap_karunati/lizmap/lizmap-modules/
    become: true

  - name: Clean temporary files from lizmap
    command: lizmap/install/clean_vartmp.sh
    become: true
    args:
      chdir: /srv/lizmap_karunati/

  - name: Set rights
    command: lizmap/install/set_rights.sh
    become: true
    args:
      chdir: /srv/lizmap_karunati/

  - name: Install lizmap again
    command: php lizmap/install/installer.php
    become: true
    args:
      chdir: /srv/lizmap_karunati/

  - name: Set rights again
    command: lizmap/install/set_rights.sh
    become: true
    args:
      chdir: /srv/lizmap_karunati/

  - name: Check http://karunati.pn971.net/
    uri:
      url: http://karunati.pn971.net/
