---
- name: Installation des serveurs
  hosts: karudata,karunati
  remote_user: karuadmin
  roles:
    - setup

- name: Installation de karunati
  hosts: karunati
  remote_user: karuadmin
  roles:
    - karunati

- name: Installation de karudata
  hosts: karudata
  remote_user: karuadmin
  roles:
    - karudata
...